# Generated by Django 5.1.4 on 2025-01-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttable',
            old_name='candidate',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='candidate_email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='candidate_name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='teachertable',
            old_name='recruiter',
            new_name='teacher',
        ),
    ]
