# Generated by Django 5.1.4 on 2025-01-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_candidate_studenttable_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttable',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='studenttable',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='teachertable',
            name='teacher_name',
        ),
    ]
