# Generated by Django 5.1.4 on 2025-05-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_teachertable_teacher_email_teachertable_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='student_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='student_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
