# Generated by Django 5.1.4 on 2025-04-18 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to='attachments/')),
                ('attachment_description', models.TextField()),
                ('attachment_name', models.CharField(max_length=100)),
                ('attachment_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='course.course')),
                ('weak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='course.timestamp')),
            ],
        ),
    ]
