# Generated by Django 5.1.4 on 2025-05-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursequiz_studentperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='course.coursequiz'),
        ),
    ]
